version: "3.3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  backend:
    build:
      context: ./passman-back
      dockerfile: Dockerfile
    restart: always
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      LOCAL_IP: ${LOCAL_IP}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:5000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - db
    volumes:
      - rsa:/app/RSA
    ports:
      - ${BACKEND_PORT}:5000

  frontend:
    build:
      context: ./passman-web
      dockerfile: Dockerfile
      args:
        BACKEND_URL: "http://${LOCAL_IP}:${BACKEND_PORT}/api/v1"
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    links:
      - backend

volumes:
  db:
    driver: local
  rsa:
    driver: local