version: "3.3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  backend:
    image: nikolai290/passman-back:latest
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:5000

      # USE FOR SEND IN EMAIL ADN USE IN CORS POLICY BY DEFAULT ALSO
      FRONTEND_URL: ${FRONTEND_URL}
      # ADVANCED CORS POLICY - NOT NECESSARILY
      # format: http://domain:port;http://domain:port;

      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_EMAIL: ${EMAIL_EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

    links:
      - db
    volumes:
      - ./RSA:/app/RSA:z
    ports:
      - ${BACKEND_PORT}:5000

  frontend:
    image: nikolai290/passman-web:latest
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    links:
      - backend
    volumes:
     - ./config:/usr/share/nginx/html/config:z

volumes:
  db:
    driver: local
  rsa:
    driver: local